<a href="https://colab.research.google.com/github/adalbertobalaoIF/colabs/blob/main/LAB02_AdalbertoBalao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratório 02 — Estrutura e Qualidade dos Dados
Objetivo: inspecionar tipos, granularidade, valores ausentes e duplicidades.

In [6]:
import pandas as pd
import seaborn as sns

dados = sns.load_dataset('penguins')
dados.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [7]:
dados.shape, dados.dtypes

((344, 7),
 species               object
 island                object
 bill_length_mm       float64
 bill_depth_mm        float64
 flipper_length_mm    float64
 body_mass_g          float64
 sex                   object
 dtype: object)

In [8]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [9]:
dados.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [10]:
dados.duplicated().sum()

np.int64(0)

## Desafio
Construa um dicionário de dados com nome, tipo, escala, unidade e papel analítico.

In [22]:
dicionario = pd.DataFrame({
    'nome': [
        'species', 'island', 'bill_length_mm', 'bill_depth_mm',
        'flipper_length_mm', 'body_mass_g', 'sex'
    ],
    'tipo': [
        'object','object','float64','float64','float64','float64','object'
    ],
    'escala': [
        'categórica nominal', 'categórica nominal',
        'quantitativa contínua', 'quantitativa contínua',
        'quantitativa contínua', 'quantitativa contínua',
        'categórica nominal'
    ],
    'unidade': [
        'espécie', 'ilha', 'milímetros', 'milímetros',
        'milímetros', 'gramas', 'pode ter ausentes'
    ],
    'papel analítico': [
        'dimensão', 'dimensão', 'medida', 'medida',
        'medida', 'medida', 'dimensão'
    ]

})
dicionario

,nome,tipo,escala,unidade,papel analítico
0,species,object,categórica nominal,espécie,dimensão
1,island,object,categórica nominal,ilha,dimensão
2,bill_length_mm,float64,quantitativa contínua,milímetros,medida
3,bill_depth_mm,float64,quantitativa contínua,milímetros,medida
4,flipper_length_mm,float64,quantitativa contínua,milímetros,medida
5,body_mass_g,float64,quantitativa contínua,gramas,medida
6,sex,object,categórica nominal,pode ter ausentes,dimensão